// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: minio.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadItem struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FileId          string                 `protobuf:"bytes,1,opt,name=fileId"`
	xxx_hidden_PresignedPutUrl string                 `protobuf:"bytes,2,opt,name=presignedPutUrl"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UploadItem) Reset() {
	*x = UploadItem{}
	mi := &file_minio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadItem) ProtoMessage() {}

func (x *UploadItem) ProtoReflect() protoreflect.Message {
	mi := &file_minio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadItem) GetFileId() string {
	if x != nil {
		return x.xxx_hidden_FileId
	}
	return ""
}

func (x *UploadItem) GetPresignedPutUrl() string {
	if x != nil {
		return x.xxx_hidden_PresignedPutUrl
	}
	return ""
}

func (x *UploadItem) SetFileId(v string) {
	x.xxx_hidden_FileId = v
}

func (x *UploadItem) SetPresignedPutUrl(v string) {
	x.xxx_hidden_PresignedPutUrl = v
}

type UploadItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FileId          string
	PresignedPutUrl string
}

func (b0 UploadItem_builder) Build() *UploadItem {
	m0 := &UploadItem{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FileId = b.FileId
	x.xxx_hidden_PresignedPutUrl = b.PresignedPutUrl
	return m0
}

type UploadToMinioRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*UploadItem         `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UploadToMinioRequest) Reset() {
	*x = UploadToMinioRequest{}
	mi := &file_minio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadToMinioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadToMinioRequest) ProtoMessage() {}

func (x *UploadToMinioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadToMinioRequest) GetItems() []*UploadItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *UploadToMinioRequest) SetItems(v []*UploadItem) {
	x.xxx_hidden_Items = &v
}

type UploadToMinioRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*UploadItem
}

func (b0 UploadToMinioRequest_builder) Build() *UploadToMinioRequest {
	m0 := &UploadToMinioRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

type DownloadFromMinioRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PresignedGetUrls []string               `protobuf:"bytes,1,rep,name=presignedGetUrls"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DownloadFromMinioRequest) Reset() {
	*x = DownloadFromMinioRequest{}
	mi := &file_minio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFromMinioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFromMinioRequest) ProtoMessage() {}

func (x *DownloadFromMinioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadFromMinioRequest) GetPresignedGetUrls() []string {
	if x != nil {
		return x.xxx_hidden_PresignedGetUrls
	}
	return nil
}

func (x *DownloadFromMinioRequest) SetPresignedGetUrls(v []string) {
	x.xxx_hidden_PresignedGetUrls = v
}

type DownloadFromMinioRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PresignedGetUrls []string
}

func (b0 DownloadFromMinioRequest_builder) Build() *DownloadFromMinioRequest {
	m0 := &DownloadFromMinioRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PresignedGetUrls = b.PresignedGetUrls
	return m0
}

type DownloadFromMinioResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FileIds []string               `protobuf:"bytes,1,rep,name=fileIds"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DownloadFromMinioResponse) Reset() {
	*x = DownloadFromMinioResponse{}
	mi := &file_minio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFromMinioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFromMinioResponse) ProtoMessage() {}

func (x *DownloadFromMinioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadFromMinioResponse) GetFileIds() []string {
	if x != nil {
		return x.xxx_hidden_FileIds
	}
	return nil
}

func (x *DownloadFromMinioResponse) SetFileIds(v []string) {
	x.xxx_hidden_FileIds = v
}

type DownloadFromMinioResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FileIds []string
}

func (b0 DownloadFromMinioResponse_builder) Build() *DownloadFromMinioResponse {
	m0 := &DownloadFromMinioResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FileIds = b.FileIds
	return m0
}

var File_minio_proto protoreflect.FileDescriptor

const file_minio_proto_rawDesc = "" +
	"\n" +
	"\vminio.proto\x12\x02pb\x1a!google/protobuf/go_features.proto\"N\n" +
	"\n" +
	"UploadItem\x12\x16\n" +
	"\x06fileId\x18\x01 \x01(\tR\x06fileId\x12(\n" +
	"\x0fpresignedPutUrl\x18\x02 \x01(\tR\x0fpresignedPutUrl\"<\n" +
	"\x14UploadToMinioRequest\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.pb.UploadItemR\x05items\"F\n" +
	"\x18DownloadFromMinioRequest\x12*\n" +
	"\x10presignedGetUrls\x18\x01 \x03(\tR\x10presignedGetUrls\"5\n" +
	"\x19DownloadFromMinioResponse\x12\x18\n" +
	"\afileIds\x18\x01 \x03(\tR\afileIdsB)Z\x1dgithub.com/criyle/go-judge/pb\x92\x03\a\xd2>\x02\x10\x03\b\x02b\beditionsp\xe8\a"

var file_minio_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_minio_proto_goTypes = []any{
	(*UploadItem)(nil),                // 0: pb.UploadItem
	(*UploadToMinioRequest)(nil),      // 1: pb.UploadToMinioRequest
	(*DownloadFromMinioRequest)(nil),  // 2: pb.DownloadFromMinioRequest
	(*DownloadFromMinioResponse)(nil), // 3: pb.DownloadFromMinioResponse
}
var file_minio_proto_depIdxs = []int32{
	0, // 0: pb.UploadToMinioRequest.items:type_name -> pb.UploadItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_minio_proto_init() }
func file_minio_proto_init() {
	if File_minio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_minio_proto_rawDesc), len(file_minio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_minio_proto_goTypes,
		DependencyIndexes: file_minio_proto_depIdxs,
		MessageInfos:      file_minio_proto_msgTypes,
	}.Build()
	File_minio_proto = out.File
	file_minio_proto_goTypes = nil
	file_minio_proto_depIdxs = nil
}
